name: odata_query
description: "OData Query Builder is a simple Dart package for building OData query strings that you can concatenate to your REST API endpoints."
version: 1.0.0
homepage: https://github.com/Arokip
repository: https://github.com/Arokip/odata_query

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
